[package]
name = "tetherd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tether-core = { path = "../tether-core" }
tether-filesystem-provider = { path = "../providers/filesystem" }
tether-process-provider = { path = "../providers/process" }
tether-search-provider = { path = "../providers/search" }
tokio = { version = "1", features = ["io-std", "io-util", "macros", "rt-multi-thread", "sync"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
